language: julia

os:
    - linux
    - osx

julia: 
    - 0.4

notifications:
    email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Merlin"); Pkg.test("Merlin"; coverage=true)'

after_success:
  - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Lapidary.jl")'
  - julia -e 'cd(Pkg.dir("Merlin")); include(joinpath("docs", "make.jl"))'
