language: julia
os:
    - linux
    - osx
julia: 
    - 0.4
    - nightly
notifications:
    email: false
script:
	- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
	- julia -e 'Pkg.clone(pwd()); Pkg.build("Merlin"); Pkg.test("Merlin"; coverage=true)'
after_success:
	- julia -e 'cd(Pkg.dir("Merlin")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';