environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x64/0.4/julia-0.4-latest-win64.exe"
  - JULIAVERSION: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia
  - set PATH=C:\msys64\usr\bin;%PATH%

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  #- set PATH=C:\mingw64\bin;%PATH%
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -F -e "versioninfo();
      Pkg.clone(pwd(), \"Merlin\"); Pkg.build(\"Merlin\")"

test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"Merlin\")"
