site_name: Merlin.jl

site_description: flexible neural network library in Julia

site_author: Hiroyuki Shindo

repo_url: https://github.com/hshindo/Merlin.jl

docs_dir: 'docs'

theme: bootstrap

extra_css:
  - css/extra.css

pages:
- Home: index.md
- Overview: overview.md
- Types: types.md
- Functors: functors.md
- Examples:
  - POS-Tagging: 'examples/pos-tagging.md'

extra_javascript:
- http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
- codehilite
- mdx_math
