name = "Merlin"
uuid = "80f3d04f-b880-5e6d-8e06-6a7e799169ac"
author = ["Hiroyuki Shindo <hshindo@outlook.com>"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
FileIO = "1.0.1"
JLD2 = "0.1.1"
CodecZlib = "0.5.0"
ProgressMeter = "0.6.0"
# @windows WinRPM

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
