name = "Merlin"
uuid = "80f3d04f-b880-5e6d-8e06-6a7e799169ac"
author = ["Hiroyuki Shindo <hshindo@outlook.com>"]

[deps]

[compat]
FileIO = "1.0.1"
JLD2 = "0.1.1"
CodecZlib = "0.5.0"
ProgressMeter = "0.6.0"
# @windows WinRPM

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
