site_name: Merlin.jl
site_description: Deep Learning Framework in Julia
site_author: Hiroyuki Shindo
repo_url: https://github.com/hshindo/Merlin.jl

docs_dir: 'build'

theme: material

python:
  version: 2 # for unicode
  setup_py_install: true

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  #- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  #- assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math:
    enable_dollar_delimiter: True #for use of inline $..$

pages:
  - Home: index.md
  - Overview: overview.md
  - Types: types.md
  - Functors: functors.md
  - Graph: graph.md
  - Optimizers: optimizers.md
#  - Examples:
#    - POS-Tagging: 'examples/pos-tagging.md'
