site_name: Merlin.jl
site_description: Flexible Neural Network Library in Julia
site_author: Hiroyuki Shindo
repo_url: https://github.com/hshindo/Merlin.jl

docs_dir: 'build'

theme: material

extra_css:
  - assets/Lapidary.css

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  #- mdx_math

pages:
  - Home: index.md
  - Overview: overview.md
  - Types: types.md
#  - Functors: functors.md
#  - Examples:
#    - POS-Tagging: 'examples/pos-tagging.md'
