site_name: Merlin.jl
site_description: Deep Learning Framework in Julia
site_author: Hiroyuki Shindo
repo_url: https://github.com/hshindo/Merlin.jl

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Overview: overview.md
  - Functions: functions.md
  - Graph: graph.md
  - Optimizers: optimizers.md
#  - GPU: gpu.md
#  - Interop with other libraries:
#    - Caffe: caffe.md
#  - Examples:
#    - POS-Tagging: 'examples/pos-tagging.md'
